#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    starter-ddev-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^starter-ddev\.ddev\.site$`)
      
      service: "starter-ddev-web-80"
      tls: false
      # middlewares:
      #   - "starter-ddev-redirectHttps"
    starter-ddev-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^starter-ddev\.ddev\.site$`)
      
      service: "starter-ddev-web-8025"
      tls: false
      # middlewares:
      #   - "starter-ddev-redirectHttps"
    starter-ddev-web-5173-http:
      entrypoints:
        - http-5172
      rule: HostRegexp(`^starter-ddev\.ddev\.site$`)
      
      service: "starter-ddev-web-5173"
      tls: false
      # middlewares:
      #   - "starter-ddev-redirectHttps"
    starter-ddev-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^starter-ddev\.ddev\.site$`)
      
      service: "starter-ddev-xhgui-80"
      tls: false
      # middlewares:
      #   - "starter-ddev-redirectHttps"
    
    
    
    
    starter-ddev-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^starter-ddev\.ddev\.site$`)
      
      service: "starter-ddev-web-80"
      
      tls: true
      
    starter-ddev-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^starter-ddev\.ddev\.site$`)
      
      service: "starter-ddev-web-8025"
      
      tls: true
      
    starter-ddev-web-5173-https:
      entrypoints:
        - http-5173
      rule: HostRegexp(`^starter-ddev\.ddev\.site$`)
      
      service: "starter-ddev-web-5173"
      
      tls: true
      
    
    starter-ddev-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^starter-ddev\.ddev\.site$`)
      
      service: "starter-ddev-xhgui-80"
      
      tls: true
      
    

  middlewares:
    starter-ddev-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    starter-ddev-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-starter-ddev-web:80
        
    starter-ddev-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-starter-ddev-web:8025
        
    starter-ddev-web-5173:
      loadbalancer:
        servers:
          - url: http://ddev-starter-ddev-web:5173
        
    
    
    
    starter-ddev-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-starter-ddev-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/starter-ddev.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/starter-ddev.key